name: Send Email Using GitHub Action

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  PROJECT_SOURCE_FOLDER: webapplication01/
  PROJECT_ZIP_FILE: package.zip

jobs:
  send-email:
    name: Send Email from GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
#       - name: Send email
#         # You may pin to the exact commit or the version.
#         # uses: dawidd6/action-send-mail@fa73d6accd067d4151b71f124ed939da15097abf
#         uses: dawidd6/action-send-mail@v3.7.2
#         with:
#           # Connection URL protocol://user:password@server:port, protocol can be smtp or smtp+starttls, replaces server_address, server_port, secure, username and password
#           connection_url: # optional
#           # SMTP server address
#           server_address: # optional
#           # SMTP server port
#           server_port: # optional, default is 25
#           # Whether this connection use TLS (default is true if server_port is 465)
#           secure: # optional
#           # Authenticate as this user to SMTP server
#           username: # optional
#           # Authenticate with this password to SMTP server
#           password: # optional
#           # Subject of mail message
#           subject: 
#           # Recipients mail addresses (separated with comma)
#           to: 
#           # Full name of mail sender (might be with an email address specified in <>)
#           from: 
#           # Body of mail message (might be a filename prefixed with file:// to read from)
#           body: # optional
#           # HTML body of mail message (might be a filename prefixed with file:// to read from)
#           html_body: # optional
#           # Carbon copy recipients (separated with comma)
#           cc: # optional
#           # Blind carbon copy recipients (separated with comma)
#           bcc: # optional
#           # An email address that will appear on the Reply-To field
#           reply_to: # optional
#           # The Message-ID this message is replying to
#           in_reply_to: # optional
#           # Allow unsigned/invalid certificates
#           ignore_cert: # optional
#           # Convert body from Markdown to HTML (set content_type input as text/html too)
#           convert_markdown: # optional
#           # Files that will be added to mail message attachments (separated with comma)
#           attachments: # optional
#           # Set Priority level for the mail message to 'high', 'normal' (default) or 'low'
#           priority: # optional
    
      - name: Zip the Test Project
        uses: vimtor/action-zip@v1
        with:
          files: ${{ env.PROJECT_SOURCE_FOLDER }}
          dest: ${{ env.PROJECT_ZIP_FILE }}
          recursive: true

      # - name: SharePoint Uploader
      #   # You may pin to the exact commit or the version.
      #   # uses: su-dont/share-point-uploader@d5219f8801329ec36b7add0d3874a9df0564c577
      #   uses: su-dont/share-point-uploader@v2.1
      #   with:
      #     # SharePoint URL
      #     sp_url: https://capgemininar.sharepoint.com/sites/PlanteMoranAppDevPilot887/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPlanteMoranAppDevPilot887%2FShared%20Documents%2FGeneral&viewid=e486d334%2D51ce%2D478f%2Dacb1%2Dc87f86d72a3f
      #     # SharePoint Username
      #     sp_username: akshatha.salian@capgemini.com
      #     # SharePoint Password
      #     sp_password: ${{secrets.SP_PASSWORD}}
      #     # SharePoint destination folder
      #     sp_folder: /Test Uploads/
      #     # SharePoint destination file name
      #     sp_file_name: FinalReport
      #     # File to be uploaded
      #     file: ${{ env.PROJECT_ZIP_FILE }}
          
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Email - Github Actions
      #     to: akshatha.salian@capgemini.com
      #     html_body: 'Hello from SMTP Action GitHub'
      #     from: GitHub_Actions
      #     body: 'Testing Report completed successfully!'
      #     #content_type: application/zip
      #     attachments: ${{ env.PROJECT_ZIP_FILE }}
          
      - name: Publish to Sharepoint
      # You may pin to the exact commit or the version.
      # uses: obrassard/action-sharepoint-publish@81f579c09846644d84642642eeb30981c2848f50
        uses: obrassard/action-sharepoint-publish@v1.1.1
        with:
          # The Sharepoint site url
          site_url: https://capgemininar.sharepoint.com/sites/PlanteMoranAppDevPilot887/
          # Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPlanteMoranAppDevPilot887%2FShared%20Documents%2FGeneral&viewid=e486d334%2D51ce%2D478f%2Dacb1%2Dc87f86d72a3f
          # Client ID to use for authentication
          sharepoint_client_id: 96c82b0c-7b8f-4507-8c6b-8e6a55334497
          # Client Secret to use for authentication
          sharepoint_client_secret: QuOYFeZTmK4ESuBxqCHxbSUrGB3eMeDHB0Zyv9qPmQ8=
          # The path where to upload the archive in the library
          library_folder: /Shared Documents/GeneralTest uploads/ # default is Shared documents
          # To upload a specific file instead of the whole repo, specify the path here
          file_path: ${{ env.PROJECT_ZIP_FILE }}